### Create Dictionary
POST http://localhost:8000/api/dict
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Chinese-English Dictionary"
}

> {%
    client.global.set("dict_id", response.body.id);
%}


### Get all dictionaries
GET http://localhost:8000/api/dict
Authorization: Bearer {{auth_token}}


### Get dictionary by id
GET http://localhost:8000/api/dict/{{dict_id}}
Authorization: Bearer {{auth_token}}


### Update dictionary by id
PUT http://localhost:8000/api/dict/{{dict_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "New name for Chinese-English Dictionary"
}


### Delete dictionary by id
DELETE http://localhost:8000/api/dict/{{dict_id}}
Authorization: Bearer {{auth_token}}
